## lines <- str_split("# Samples Generated by Stan
## #
## # stan_version_major=1
## # stan_version_minor=0
## # stan_version_patch=2
## # data=
## # init=random initialization
## # append_samples=0
## # save_warmup=0
## # seed=184502662
## # chain_id=1
## # iter=2000
## # warmup=1000
## # thin=1
## # equal_step_sizes=0
## # leapfrog_steps=-1
## # max_treedepth=10
## # epsilon=-1
## # epsilon_pm=0
## # delta=0.5
## # gamma=0.05
## #
## lp__,treedepth__,stepsize__,y
## # (mcmc::nuts_diag) adaptation finished
## # step size=2.15443
## # parameter step size multipliers:
## # 1
## -0.0196497,1,2.15443,0.198241", "\n")[[1]]
## StanExtras:::parse_stan_header_lines(lines)


