context("parse_stan_header_lines")
library(stringr)

lines <- str_split("# Samples Generated by Stan
#
# stan_version_major=1
# stan_version_minor=0
# stan_version_patch=2
# data=data.R
# init=random initialization
# append_samples=0
# save_warmup=0
# seed=1234567
# chain_id=1
# iter=2200
# warmup=2000
# thin=1
# equal_step_sizes=0
# leapfrog_steps=-1
# max_treedepth=10
# epsilon=-1
# epsilon_pm=0
# delta=0.5
# gamma=0.05
#
lp__,treedepth__,stepsize__,alpha,beta,sigma
# (mcmc::nuts_diag) adaptation finished
# step size=0.0260123
# parameter step size multipliers:
# 0.00280567,0.00149405,1.73205", "\n")[[1]]

test_that("parse_stan_header_lines works", {
    x <- StanExtras:::parse_stan_header_lines(lines)
    test_is(x, "list")
    test_equal(names(x), c("chains", "par_chains"))
})



